/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#00164d",
        "surface-dim": "#d8dadc",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#1bc768",
        "tertiary": "#2f56c3",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#67fe98",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#bbcbba",
        "on-secondary-fixed": "#002021",
        "on-tertiary-container": "#0037a1",
        "secondary-fixed": "#82f4f7",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#64d8da",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007072",
        "on-primary-container": "#004c23",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#004f51",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "tertiary-container": "#92aaff",
        "secondary-container": "#82f4f7",
        "inverse-primary": "#45e17e",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "on-surface-variant": "#3d4a3e",
        "error": "#ba1a1a",
        "outline": "#6c7b6d",
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#45e17e",
        "surface-tint": "#006d35",
        "primary": "#006d35",
        "secondary": "#00696c",
        "on-primary-fixed-variant": "#005226",
        "tertiary-fixed-dim": "#b5c4ff",
        "on-primary-fixed": "#00210c",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed-variant": "#053caa",
        "tertiary-fixed": "#dce1ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}